name = "test-yahoo-collector-0300-2200-utc"
main = "src/index.js"
compatibility_date = "2026-08-27"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/15 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "munotstadt_test"
database_id = "4876695b-8ea2-4283-b49b-853880bbcfb9"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "46d4e19345cb4455b630d429b9884e2a"
